# Generated by Django 2.2.6 on 2019-11-27 17:06

from django.db import migrations, models
import django.db.models.deletion
import juntagrico.entity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juntagrico', '0019_auto_20191127_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False, verbose_name='bezahlt')),
                ('bill_date', models.DateField(blank=True, null=True, verbose_name='Aktivierungssdatum')),
                ('ref_number', models.CharField(max_length=30, unique=True, verbose_name='Referenznummer')),
                ('amount', models.FloatField(verbose_name='Betrag')),
                ('billable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='juntagrico.Billable')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_account', models.CharField(max_length=10, verbose_name='Debitor-Konto')),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTypeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, verbose_name='Konto')),
                ('subscriptiontype', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptiontype_account', to='juntagrico.SubscriptionType')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Bezahldatum')),
                ('amount', models.FloatField(verbose_name='Betrag')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='juntagrico_billing.Bill')),
            ],
            options={
                'verbose_name': 'Zahlung',
                'verbose_name_plural': 'Zahlungen',
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, verbose_name='Konto')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_account', to='juntagrico.Member')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraSubscriptionCategoryAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, verbose_name='Konto')),
                ('extrasubcategory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extrasub_account', to='juntagrico.ExtraSubscriptionCategory')),
            ],
        ),
    ]
