# Generated by Django 2.2.6 on 2020-02-29 21:11

from django.db import migrations, models
import django.db.models.deletion
import juntagrico.entity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juntagrico', '0021_auto_20200229_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(unique=True, verbose_name='start date')),
                ('name', models.CharField(blank='True', max_length=20, null=True, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Business Year',
                'verbose_name_plural': 'Business Years',
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_account', models.CharField(max_length=10, verbose_name='Debitor-Konto')),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTypeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, verbose_name='Konto')),
                ('subscriptiontype', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptiontype_account', to='juntagrico.SubscriptionType')),
            ],
        ),
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, verbose_name='Konto')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_account', to='juntagrico.Member')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraSubscriptionCategoryAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, verbose_name='Konto')),
                ('extrasubcategory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extrasub_account', to='juntagrico.ExtraSubscriptionCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported', models.BooleanField(default=False, verbose_name='exported')),
                ('bill_date', models.DateField(blank=True, null=True, verbose_name='Billing date')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment date')),
                ('paid_amount', models.FloatField(blank=True, null=True, verbose_name='Paid amount')),
                ('public_notes', models.TextField(blank=True, null=True, verbose_name='Notes visible to Mitglieder')),
                ('private_notes', models.TextField(blank=True, null=True, verbose_name='Notes not visible to Mitglieder')),
                ('billable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='juntagrico.Billable', verbose_name='Billable object')),
                ('business_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='juntagrico_billing.BusinessYear', verbose_name='Business Year')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
    ]
