# Generated by Django 3.0.3 on 2020-03-15 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessyear',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 12, 31), verbose_name='end date'),
            preserve_default=False,
        ),
    ]
