# Generated by Django 3.2.2 on 2021-11-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_billing', '0001_squashed_0012_post_1_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
    ]
