# Generated by Django 3.0.5 on 2020-05-01 08:17

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='paid',
        ),
        migrations.AddField(
            model_name='businessyear',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 5, 1), verbose_name='end date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessyear',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment date'),
        ),
    ]
