# Generated by Django 3.1.1 on 2020-10-25 16:39

import datetime

import django.db.models.deletion
import juntagrico.entity
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0027_auto_20200921_0817'),
        ('juntagrico_billing', '0002_auto_20200501_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Rechnung', 'verbose_name_plural': 'Rechnungen'},
        ),
        migrations.AlterModelOptions(
            name='businessyear',
            options={'verbose_name': 'Geschäftsjahr', 'verbose_name_plural': 'Geschäftsjahre'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Zahlung', 'verbose_name_plural': 'Zahlung'},
        ),
        migrations.RemoveField(
            model_name='bill',
            name='billable',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='exported',
        ),
        migrations.AddField(
            model_name='bill',
            name='booking_date',
            field=models.DateField(default=datetime.date(2020, 1, 1), verbose_name='Booking date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='juntagrico.member', verbose_name='Mitglied'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Bezahlt'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Betrag'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(default=datetime.date(2020, 1, 1), verbose_name='Rechungsdatum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='business_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='juntagrico_billing.businessyear', verbose_name='Geschäftsjahr'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='private_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notizen nicht sichtbar für Mitglieder'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='public_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notizen sichtbar für Mitglieder'),
        ),
        migrations.AlterField(
            model_name='businessyear',
            name='end_date',
            field=models.DateField(verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='businessyear',
            name='start_date',
            field=models.DateField(unique=True, verbose_name='Startdatum'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Betrag'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='juntagrico_billing.bill', verbose_name='Rechnung'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Zahlungsdatum'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='private_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notizen nicht sichtbar für Mitglieder'),
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('amount', models.FloatField(default=0.0, verbose_name='Betrag')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='juntagrico_billing.bill', verbose_name='Rechnung')),
                ('extrasubscription_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='juntagrico.extrasubscriptiontype', verbose_name='Extrasubscription')),
                ('subscription_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='juntagrico.subscriptiontype', verbose_name='Subscription')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
    ]
