# Generated by Django 3.1.1 on 2020-10-31 17:23

from django.db import migrations, models
import django.db.models.deletion
import juntagrico.entity


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0027_auto_20200921_0817'),
        ('juntagrico_billing', '0003_auto_20201025_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.TextField(blank=True, null=True, verbose_name='IBAN')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('booking_account', models.TextField(verbose_name='Buchungskonto')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
        migrations.AlterField(
            model_name='bill',
            name='booking_date',
            field=models.DateField(verbose_name='Buchungsdatum'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='extrasubscription_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='juntagrico.extrasubscriptiontype', verbose_name='Zusatzabo'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='subscription_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='juntagrico.subscriptiontype', verbose_name='Abo'),
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='juntagrico_billing.paymenttype', verbose_name='Payment type'),
            preserve_default=False,
        ),
    ]
