# Generated by Django 4.2.17 on 2025-02-26 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_billing', '0003_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='balancing_paymenttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_balancing_paymenttype', to='juntagrico_billing.paymenttype'),
        ),
    ]
