# Generated by Django 4.2.20 on 2025-04-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("juntagrico_billing", "0004_settings_balancing_paymenttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="balancing_paymenttype",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings_balancing_paymenttype",
                to="juntagrico_billing.paymenttype",
                verbose_name="Zahlungstyp für Rechnungsausgleich",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="default_paymenttype",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="juntagrico_billing.paymenttype",
                verbose_name="Standard Zahlungstyp",
            ),
        ),
    ]
