# Generated by Django 4.2.25 on 2026-01-08 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_billing', '0005_alter_settings_balancing_paymenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='contribution_itemtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_contribution_itemtype', to='juntagrico_billing.billitemtype', verbose_name='Bill Item Type for contributions from juntagrico-contribution'),
        ),
    ]
