# Generated by Django 3.1.1 on 2020-11-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_billing', '0005_auto_20201031_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='booking_account',
            field=models.CharField(max_length=10, verbose_name='Buchungskonto'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='iban',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
    ]
