# Generated by Django 4.2.27 on 2026-02-06 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_billing', '0005_alter_settings_balancing_paymenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_date',
            field=models.DateField(default=datetime.date(2026, 1, 1), verbose_name='Zahlungsdatum'),
            preserve_default=False,
        ),
    ]
