# Generated by Django 5.2.17 on 2026-09-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_billing', '0006_alter_payment_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='Verworfene Rechnungen werden Mitgliedern nicht angezeigt und sind von der Buchhaltung ausgenommen.', verbose_name='Verworfen'),
        ),
    ]
