# Generated by Django 3.1.1 on 2021-01-16 20:28

from django.db import migrations, models
import django.db.models.deletion
import juntagrico.entity


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_billing', '0007_bill_notification_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('booking_account', models.CharField(max_length=10, verbose_name='Buchungskonto')),
            ],
            options={
                'verbose_name': 'Custom Bill-Item Type',
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
        migrations.AlterField(
            model_name='bill',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Benachrichtigung versandt'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='custom_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='juntagrico_billing.billitemtype', verbose_name='BillItemType'),
        ),
    ]
