# Generated by Django 3.1.1 on 2021-02-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_billing', '0008_bill_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unique Id'),
        ),
    ]
