# Generated by Django 3.1.1 on 2021-03-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_billing', '0008_bill_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='unique_id',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Eindeutige Id'),
        ),
    ]
