# Generated by Django 3.1.1 on 2021-01-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_billing', '0008_bill_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Beschreibung'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billitemtype',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
