# Generated by Django 3.2 on 2021-04-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0032_data_1_4'),
        ('juntagrico_billing', '0009_payment_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='subscription_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='juntagrico.subscriptionpart', verbose_name='Abo Bestandteil'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Eindeutige Id'),
        ),
    ]
