# Generated by Django 3.2 on 2021-04-18 17:16
import datetime
from django.db import migrations
from collections import defaultdict
import logging

logger = logging.getLogger(__name__)


def migrate_bill_items(apps, schema_editor):
    """
    change bill items to reference subscription parts
    instead of subscription types or extrasubscription types
    """
    logger.info('migrate_bill_items')
    BillItem = apps.get_model('juntagrico_billing', 'BillItem')
    SubscriptionPart = apps.get_model('juntagrico', 'SubscriptionPart')

    # build dict of active subscription parts
    # with key (member, productname) for lookup
    parts_per_member_and_prod = defaultdict(list)
    for part in SubscriptionPart.objects.filter(activation_date__gte=datetime.date(2021, 1, 1)):
        key = (part.subscription.primary_member, part.type.size.product.name)
        parts_per_member_and_prod[key].append(part)

    logger.info('built subscription parts dict (%d)' % len(parts_per_member_and_prod))

    for itm in BillItem.objects.all():
        member = itm.bill.member
        key = None
        if itm.subscription_type:
            # migrate subscription BillItem
            key = (member, itm.subscription_type.size.product.name)
        elif itm.extrasubscription_type:
            # migrate extrasubscription BillItem
            # we find the matching part by member
            # and category name
            key = (member, itm.extrasubscription_type.category.name)
        try:
            parts_list = parts_per_member_and_prod[key]
        except KeyError:
            logger.error(f'no subscription_parts found for extrasubscription_type {key}')

        if parts_list:
            # we need to remove used parts from our dictionary list
            itm.subscription_part = parts_list.pop()
        else:
            logger.error(f"unexpectedly empty parts_list for {key}")
        itm.save()


def migrate_extrasubscription_accounts(apps, schema_editor):
    """
    create new subscription type account objects for each
    extrasubscription category account
    """
    SubscriptionType = apps.get_model('juntagrico', 'SubscriptionType')
    ExtraSubscriptionCategoryAccount = apps.get_model('juntagrico_billing', 'ExtraSubscriptionCategoryAccount')
    SubscriptionTypeAccount = apps.get_model('juntagrico_billing', 'SubscriptionTypeAccount')

    type_by_name = dict([
        (subtype.size.product.name, subtype) for
        subtype in SubscriptionType.objects.filter(size__product__is_extra=True)
    ])
    logger.info('created type by name dict (%d)' % len(type_by_name))

    for e_acct in ExtraSubscriptionCategoryAccount.objects.all():
        name = e_acct.extrasubcategory.name
        acct_data = {
            'subscriptiontype': type_by_name[name],
            'account': e_acct.account
        }
        SubscriptionTypeAccount.objects.create(**acct_data)
        logger.info('migrated ExtraSubscriptionCategoryAccount %s, account %s' % (name, e_acct.account))


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0032_data_1_4'),
        ('juntagrico_billing', '0010_pre_1_4'),
    ]

    operations = [
        migrations.RunPython(migrate_bill_items),
        migrations.RunPython(migrate_extrasubscription_accounts)
    ]
