# Generated by Django 3.2 on 2021-04-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0032_data_1_4'),
        ('juntagrico_billing', '0011_data_1_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='extrasubscription_type',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='subscription_type',
        ),
        migrations.DeleteModel(
            name='ExtraSubscriptionCategoryAccount',
        ),
    ]
